### ISSUE TITLE
Is arm64 supported by the Docker image?

### ISSUE THREAD

**Issue by rockhigher** [citra-emu/citra-multiplayer-dedicated#7]
Hi,

I would just like to clarify if this docker image supports arm64 operating systems?

When trying to run a new container with the image in Docker (I used the commands from the [Multiplayer Rooms page](https://citra-emu.org/help/feature/multiplayer/), I encounter the following error
`standard_init_linux.go:211: exec user process caused "exec format error"`

Or is there an alternative/workaround that I can try, whether it is supported or not?

Thanks

**Comment by liushuyu** [comment]
Hi there,

Currently, the provided Docker image only supports `amd64` architecture. I can try to build images for other architectures if you want.

**Comment by rockhigher** [comment]
Hi,

Yes, that would be awesome! I would highly appreciate it (and others in the future who might stumble upon this)

Thanks

**Comment by datsoy** [comment]
Any update for the arm64 build?

**Comment by liushuyu** [comment]
Sorry for the late response, the arm64 version of the image is now available.

![Screenshot](https://user-images.githubusercontent.com/6829345/138383636-557560c8-9a08-46e9-92d9-d841e131d22e.png)
